### ISSUE TITLE
Metaspace size increasing continuously when running in Tomcat

### ISSUE THREAD

**Issue by zoell** [pierredavidbelanger/logback-awslogs-appender#21]
Hi,

I am running an app in Tomcat and when using this logger the Metaspace (permgen) memory space size is continuously increasing and GC is never able to clear these classes. Hence Tomcat will die at some point because of out of memory. (increasing metaspace size is not a solution for this)

Is it just me?
When I remove this logger everything is back to normal.

Thanks,
zoell

**Comment by pierredavidbelanger** [comment]
I had this problem in the past, using old version of tomcat along with old version of java (pre 1.6 I guess) and an abuse of groovy classes.

Its a long time since I saw this to be honnest.

Please, tel me what JVM and Tomcat version you are using, and if possible, please run your application locally and profile it with visualvm, and try to have a look at whats inside the permgen

**Comment by zoell** [comment]
Apache Tomcat/8.5.38
JVM 1.8.0_181

Basically I am just running it within the Docker image tomcat:8.5.38-jre8

**Comment by pierredavidbelanger** [comment]
This projet does not create anything dynamic (in the Metaspace), so I guess its one of its dependency.

[This thread](https://stackoverflow.com/questions/38342418/outofmemoryerror-when-creating-amazons3client-in-lambda) seems to be somewhat related.

**Comment by pierredavidbelanger** [comment]
Did you tried to run your application with a profiler attached ?

Alos, since you are using Docker, you may want to consider the use of [Docker's CloudWatch logging driver](https://docs.docker.com/config/containers/logging/awslogs/). This will unload the logging burden from your application. I do this myself for my own projets.

I will soon close this issue, since I fail to understand why my code would fill the metaspace.
